# .github/workflows/deploy.yml
name: Deploy PWA to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          # ref: main
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install and Build and Deploy 🔧
        run: |
          npm install yarn -g 
          yarn 
          yarn build:static  

      - name: Deploy 🚀
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/sarahBuisson/content-generator2.git
          npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
